schema: "classroom50/repo-config/v1"
classroom: "144-web-dev-i"
assignment: "tutorial-3-notes"
owner:
  username: "TaykiaHayes1"
  id: 321918974
  accepted_at: "2026-10-07T16:50:49Z"
source:
  owner: "144Fa26"
  owner_id: 299228787
  repo: "tutorial3notes"
  branch: "main"
